#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    if len(ar) == 0:
        return 0       
    ColorStock = {ar[0]:1}
    for i in range(1, n):
        if ColorStock.get(ar[i]) == None:
            ColorStock[ar[i]] = 1
        else:
            ColorStock[ar[i]] += 1      
    Pairs = 0 
    for j in ColorStock:
        Pairs += int(ColorStock[j]/2)
    return Pairs

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
