#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    Level = 0
    Valley = 0
    for i in range(n):
        if Level == 0:
            if s[i] == 'D':
                Valley += 1
                Level -= 1
            else:
                Level += 1
        else:
            if s[i] == 'D':
                Level -= 1
            else:
                Level += 1
    return Valley




if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()
    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
